version: '3.8'
services:
  eureka-server:
    image: eureka-server:latest
    build: eureka-server
    ports:
      - "8761:8761"

  userservice:
    image: userservice
    build:
      context: ./userservice
    ports:
      - "8081:8080"

networks:
  default:
    driver: bridge