server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  profiles:
    active: dev, default
  application:
        name: config-service
  cloud:
      discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      show-components: always